#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width           2
bspc config window_gap             12

bspc config normal_border_color    "#0A1F32"
bspc config active_border_color    "#2D384A"
bspc config focused_border_color   "#344756"

bspc config presel_feedback_color  "#595B82"

bspc config focus_follows_pointer  true
bspc config pointer_modifier       super

bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc rule -a Krita desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
